### ISSUE TITLE
Baker-Hubbard docs not working

### ISSUE THREAD

**Issue by p1224recursion** [mdtraj/mdtraj#1702]
Hello,

The page at
https://www.mdtraj.org/1.9.5/examples/hbonds.html

does not show code, it appears the source notebook is not being read correctly.

**Comment by mattwthompson** [comment]
Looks like the website is pointing to an old version of the docs; I don't think 1.9.7 docs have been built but I thought there were 1.9.6. docs floating around somewhere. This was fixed sometime in the past year in recent PRs (not sure which ones off the top of my head).

**Comment by rmcgibbo** [comment]
It looks like this is still broken even on the latest build of the docs.
